"""Live canary mutation checks for the private canary repository."""

from __future__ import annotations

import time
from uuid import uuid4

import pytest
import requests

from .github_mutation import (
    close_mutation_pr,
    create_mutation_branch,
    create_mutation_pr,
    delete_mutation_branch,
    upsert_mutation_file,
)
from .repo_config import GITHUB_API_URL, JsonObject

pytestmark = pytest.mark.private_canary


def _run_id() -> str:
    return f"{int(time.time())}-{uuid4().hex[:8]}"


def _repo_or_skip(repo: str, github_client: requests.Session) -> JsonObject:
    response = github_client.get(f"{GITHUB_API_URL}/repos/{repo}")
    if response.status_code == 404:
        pytest.skip(f"Private canary repo is unavailable (404): {repo}")
    if response.status_code == 403:
        pytest.skip(f"Private canary repo is not accessible (403): {repo}. Token may lack repo scope.")
    response.raise_for_status()
    payload = response.json()
    assert isinstance(payload, dict), f"Malformed repository payload for {repo}: {payload!r}"
    return payload


def _default_branch_and_sha(repo: str, github_client: requests.Session) -> tuple[str, str]:
    repo_payload = _repo_or_skip(repo, github_client)
    default_branch = repo_payload.get("default_branch")
    assert isinstance(default_branch, str), f"{repo}: missing default_branch"

    ref_response = github_client.get(f"{GITHUB_API_URL}/repos/{repo}/git/ref/heads/{default_branch}")
    ref_response.raise_for_status()
    ref_payload = ref_response.json()
    assert isinstance(ref_payload, dict), f"{repo}: malformed ref payload"
    ref_target = ref_payload.get("object")
    assert isinstance(ref_target, dict), f"{repo}: malformed ref target"
    sha = ref_target.get("sha")
    assert isinstance(sha, str), f"{repo}: missing default branch SHA"
    return default_branch, sha


def test_private_canary_repo_is_reachable_and_mutable(
    github_client: requests.Session, canary_private_repo: str
) -> None:
    run_id = _run_id()
    branch = f"feat/e2e-private-canary-{run_id}"
    pr_number: int | None = None
    branch_created = False

    try:
        default_branch, sha = _default_branch_and_sha(canary_private_repo, github_client)

        create_mutation_branch(canary_private_repo, branch, sha, github_client)
        branch_created = True

        upsert_mutation_file(
            canary_private_repo,
            f"e2e/private-canary-{run_id}.txt",
            f"private canary mutation test {run_id}\n",
            f"test: add private canary fixture for {branch}",
            branch,
            github_client,
        )

        pr = create_mutation_pr(
            canary_private_repo,
            f"test: e2e private canary PR {run_id}",
            branch,
            default_branch,
            "## Changes\n\nLive private canary PR generated by the e2e test suite.",
            github_client,
        )

        number = pr.get("number")
        assert isinstance(number, int), f"Malformed PR payload without number: {pr!r}"
        pr_number = number

        pr_response = github_client.get(f"{GITHUB_API_URL}/repos/{canary_private_repo}/pulls/{pr_number}")
        pr_response.raise_for_status()
        pr_payload = pr_response.json()
        assert isinstance(pr_payload, dict), f"Malformed PR response: {pr_payload!r}"
        assert pr_payload.get("state") == "open", f"Expected PR to be open, got: {pr_payload.get('state')}"

    finally:
        close_error: requests.HTTPError | None = None
        if pr_number is not None:
            try:
                close_mutation_pr(canary_private_repo, pr_number, github_client)
            except requests.HTTPError as error:
                close_error = error

        if branch_created:
            delete_mutation_branch(canary_private_repo, branch, github_client)

        if close_error is not None:
            raise close_error
