"""Live E2E tests for GitHub's mergeability API."""

from __future__ import annotations

import time
from typing import cast

import pytest
import requests

from .conftest import (
    GITHUB_API_URL,
    create_mutation_branch,
    create_mutation_pr,
    delete_mutation_branch,
    guard_mutation,
    upsert_mutation_file,
)
from .test_canary_pr import (
    CHECK_BRANCH_NAME,
    CHECK_GITLEAKS,
    CHECK_PR_TITLE,
    REQUIRED_PASSING_CHECKS,
    _assert_check_conclusion,
    _close_mutation_pr,
    _default_branch_and_sha,
    _run_id,
    wait_for_checks,
)

pytestmark = pytest.mark.mergeability

JsonObject = dict[str, object]


def _poll_mergeable_state(
    repo: str,
    pr_number: int,
    github_client: requests.Session,
    timeout_seconds: int = 120,
    interval_seconds: int = 5,
) -> JsonObject:
    """Poll a PR until GitHub computes its mergeable field or timeout is reached.

    GitHub computes mergeability asynchronously, so the initial GET may return
    ``mergeable: null``. This helper retries until the field is populated or
    the deadline expires.
    """
    deadline = time.monotonic() + timeout_seconds
    while True:
        response = github_client.get(f"{GITHUB_API_URL}/repos/{repo}/pulls/{pr_number}")
        response.raise_for_status()
        pr = cast(JsonObject, response.json())
        mergeable = pr.get("mergeable")
        if mergeable is not None:
            return pr
        if time.monotonic() >= deadline:
            raise TimeoutError(
                f"{repo}#{pr_number}: mergeable field was not computed within "
                f"{timeout_seconds}s"
            )
        time.sleep(interval_seconds)


def _create_canary_pr(
    repo: str,
    branch: str,
    path: str,
    content: str,
    title: str,
    github_client: requests.Session,
) -> tuple[str, int]:
    """Create a canary branch, file, and PR in an allowlisted repository."""
    guard_mutation(repo)
    default_branch, sha = _default_branch_and_sha(repo, github_client)
    _ = create_mutation_branch(repo, branch, sha, github_client)
    _ = upsert_mutation_file(
        repo,
        path,
        content,
        f"test: add canary fixture for {branch}",
        branch,
        github_client,
    )
    pr = create_mutation_pr(
        repo,
        title,
        branch,
        default_branch,
        "## Changes\n\nLive canary PR generated by the e2e test suite.",
        github_client,
    )
    number = pr.get("number")
    assert isinstance(number, int), f"Malformed PR payload without number: {pr!r}"
    return default_branch, number


def test_valid_pr_is_mergeable(github_client: requests.Session, canary_public_repo: str) -> None:
    """A valid PR (conventional title, valid branch) should be reported as mergeable."""
    run_id = _run_id()
    branch = f"feature/test-merge-{run_id}"
    pr_number: int | None = None

    try:
        _, pr_number = _create_canary_pr(
            canary_public_repo,
            branch,
            f"e2e/mergeable-{run_id}.txt",
            f"mergeability canary change {run_id}\n",
            "feat: test mergeability",
            github_client,
        )

        # Wait for required checks to finish (pr-checks + gitleaks)
        checks = wait_for_checks(canary_public_repo, pr_number, github_client)
        for check_name in REQUIRED_PASSING_CHECKS:
            _assert_check_conclusion(checks, check_name, "success")

        # Poll until GitHub computes mergeability
        pr = _poll_mergeable_state(canary_public_repo, pr_number, github_client)

        mergeable = pr.get("mergeable")
        assert mergeable is True, f"Expected mergeable=True, got {mergeable!r}"

        mergeable_state = pr.get("mergeable_state")
        assert isinstance(mergeable_state, str), (
            f"Expected mergeable_state to be a string, got {mergeable_state!r}"
        )
        allowed_states = {"clean", "has_hooks", "unstable"}
        assert mergeable_state in allowed_states, (
            f"mergeable_state {mergeable_state!r} not in allowed set {allowed_states}"
        )
        assert mergeable_state != "blocked", (
            f"Valid PR should not be blocked, got {mergeable_state!r}"
        )
    finally:
        if pr_number is not None:
            _close_mutation_pr(canary_public_repo, pr_number, github_client)
        delete_mutation_branch(canary_public_repo, branch, github_client)


def test_invalid_title_pr_is_blocked(github_client: requests.Session, canary_public_repo: str) -> None:
    """A PR with an invalid title should be reported as unmergeable (blocked)."""
    run_id = _run_id()
    branch = f"feature/test-merge-invalid-{run_id}"
    pr_number: int | None = None

    try:
        _, pr_number = _create_canary_pr(
            canary_public_repo,
            branch,
            f"e2e/mergeable-invalid-{run_id}.txt",
            f"mergeability invalid canary change {run_id}\n",
            "bad title no prefix",
            github_client,
        )

        # Wait for checks; title check should fail
        checks = wait_for_checks(
            canary_public_repo,
            pr_number,
            github_client,
            expected_checks=(CHECK_PR_TITLE, CHECK_BRANCH_NAME, CHECK_GITLEAKS),
        )
        _assert_check_conclusion(checks, CHECK_PR_TITLE, "failure")
        _assert_check_conclusion(checks, CHECK_BRANCH_NAME, "success")

        # Poll until GitHub computes mergeability
        pr = _poll_mergeable_state(canary_public_repo, pr_number, github_client)

        mergeable = pr.get("mergeable")
        mergeable_state = pr.get("mergeable_state")
        assert isinstance(mergeable_state, str), (
            f"Expected mergeable_state to be a string, got {mergeable_state!r}"
        )

        # GitHub may report mergeable=False (conflicts) or mergeable=True with
        # mergeable_state="blocked" (branch protection). Either is acceptable.
        assert mergeable is False or mergeable_state == "blocked", (
            f"Invalid-title PR should not be mergeable: mergeable={mergeable!r}, "
            f"mergeable_state={mergeable_state!r}"
        )
    finally:
        if pr_number is not None:
            _close_mutation_pr(canary_public_repo, pr_number, github_client)
        delete_mutation_branch(canary_public_repo, branch, github_client)
