"""Live and static checks for the privileged security review workflow."""

from __future__ import annotations

import re
import time
from collections.abc import Callable, Mapping
from pathlib import Path
from typing import cast
from uuid import uuid4

import pytest
import requests

from . import conftest as live_fixtures

pytestmark = pytest.mark.security_review

GITHUB_API_URL = live_fixtures.GITHUB_API_URL
SECURITY_WORKFLOW_PATH = ".github/workflows/security/pr-review.yml"
SECURITY_WORKFLOW_ID = "security%2Fpr-review.yml"
ACCEPTABLE_SECURITY_REVIEW_CONCLUSIONS = {"success", "failure", "skipped"}

JsonObject = dict[str, object]
GithubMutation = Callable[..., requests.Response]

_github_mutation_post = cast(GithubMutation, live_fixtures.github_mutation_post)
_github_mutation_patch = cast(GithubMutation, live_fixtures.github_mutation_patch)


def _raise_for_response(response: requests.Response, context: str) -> None:
    if response.status_code >= 400:
        raise AssertionError(f"{context} failed: {response.status_code}: {response.text[:500]}")


def _repo_or_skip(repo: str, github_client: requests.Session) -> JsonObject:
    response = github_client.get(f"{GITHUB_API_URL}/repos/{repo}")
    if response.status_code == 404:
        pytest.skip(f"Canary repo is unavailable: {repo}")
    _raise_for_response(response, f"read repo {repo}")
    payload = cast(object, response.json())
    assert isinstance(payload, dict), f"Malformed repository payload for {repo}: {payload!r}"
    return cast(JsonObject, payload)


def _default_branch_and_sha(repo: str, github_client: requests.Session) -> tuple[str, str]:
    repo_payload = _repo_or_skip(repo, github_client)
    default_branch = repo_payload.get("default_branch")
    assert isinstance(default_branch, str), f"{repo}: missing default_branch"

    response = github_client.get(f"{GITHUB_API_URL}/repos/{repo}/git/ref/heads/{default_branch}")
    _raise_for_response(response, f"read default branch ref for {repo}")
    ref_payload = cast(object, response.json())
    assert isinstance(ref_payload, dict), f"{repo}: malformed ref payload"
    ref_object = cast(Mapping[str, object], ref_payload)
    obj = ref_object.get("object")
    assert isinstance(obj, dict), f"{repo}: malformed ref object"
    object_payload = cast(Mapping[str, object], obj)
    sha = object_payload.get("sha")
    assert isinstance(sha, str), f"{repo}: missing default branch SHA"
    return default_branch, sha


def _run_id() -> str:
    return f"{int(time.time())}-{uuid4().hex[:8]}"


def _create_security_canary_pr(
    repo: str,
    branch: str,
    run_id: str,
    github_client: requests.Session,
) -> int:
    live_fixtures.guard_mutation(repo)
    default_branch, sha = _default_branch_and_sha(repo, github_client)
    _ = live_fixtures.create_mutation_branch(repo, branch, sha, github_client)
    _ = live_fixtures.upsert_mutation_file(
        repo,
        f"e2e/security-review-{run_id}.md",
        f"# Security review canary\n\nHarmless canary change for {run_id}.\n",
        f"test: add security review canary for {run_id}",
        branch,
        github_client,
    )
    pr = live_fixtures.create_mutation_pr(
        repo,
        "test: e2e security review label workflow",
        branch,
        default_branch,
        "## Changes\n\nLive security-review canary PR generated by the e2e test suite.",
        github_client,
    )
    number = pr.get("number")
    assert isinstance(number, int), f"Malformed PR payload without number: {pr!r}"
    return number


def _add_security_review_label(repo: str, pr_number: int, github_client: requests.Session) -> None:
    response = _github_mutation_post(
        github_client,
        repo,
        f"{GITHUB_API_URL}/repos/{repo}/issues/{pr_number}/labels",
        json={"labels": ["security-review"]},
    )
    _raise_for_response(response, f"add security-review label to {repo}#{pr_number}")


def _close_mutation_pr(repo: str, pr_number: int, github_client: requests.Session) -> None:
    response = _github_mutation_patch(
        github_client,
        repo,
        f"{GITHUB_API_URL}/repos/{repo}/pulls/{pr_number}",
        json={"state": "closed"},
    )
    if response.status_code == 404:
        return
    _raise_for_response(response, f"close PR {repo}#{pr_number}")


def _latest_security_review_run_for_branch(
    repo: str,
    branch: str,
    github_client: requests.Session,
) -> JsonObject | None:
    response = github_client.get(
        f"{GITHUB_API_URL}/repos/{repo}/actions/workflows/{SECURITY_WORKFLOW_ID}/runs",
        params={"branch": branch, "event": "pull_request_target", "per_page": 10},
    )
    if response.status_code == 404:
        pytest.skip(f"{repo} does not expose {SECURITY_WORKFLOW_ID} workflow runs")
    _raise_for_response(response, f"list security review workflow runs for {repo}@{branch}")

    payload = cast(object, response.json())
    assert isinstance(payload, dict), f"{repo}@{branch}: malformed workflow-runs payload"
    payload_mapping = cast(Mapping[str, object], payload)
    workflow_runs = payload_mapping.get("workflow_runs")
    assert isinstance(workflow_runs, list), f"{repo}@{branch}: missing workflow_runs list"

    for run in cast(list[object], workflow_runs):
        if not isinstance(run, dict):
            continue
        run_payload = cast(JsonObject, run)
        if run_payload.get("path") == SECURITY_WORKFLOW_PATH or run_payload.get("head_branch") == branch:
            return run_payload
    return None


def _wait_for_security_review_run(
    repo: str,
    branch: str,
    github_client: requests.Session,
    timeout: int = 300,
) -> JsonObject:
    deadline = time.monotonic() + timeout
    last_run: JsonObject | None = None
    while time.monotonic() < deadline:
        last_run = _latest_security_review_run_for_branch(repo, branch, github_client)
        if last_run and last_run.get("status") == "completed":
            return last_run
        time.sleep(15)
    raise TimeoutError(f"{repo}@{branch}: security review workflow did not complete within {timeout}s: {last_run}")


def test_security_review_label_triggers_workflow(
    github_client: requests.Session,
    canary_public_repo: str,
) -> None:
    run_id = _run_id()
    branch = f"test/e2e-security-review-{run_id}"
    pr_number: int | None = None
    try:
        pr_number = _create_security_canary_pr(canary_public_repo, branch, run_id, github_client)
        _add_security_review_label(canary_public_repo, pr_number, github_client)

        run = _wait_for_security_review_run(canary_public_repo, branch, github_client)
        conclusion = run.get("conclusion")
        assert conclusion in ACCEPTABLE_SECURITY_REVIEW_CONCLUSIONS, (
            f"Security review workflow reached unacceptable conclusion for {canary_public_repo}@{branch}: {run}"
        )
    finally:
        if pr_number is not None:
            _close_mutation_pr(canary_public_repo, pr_number, github_client)
        live_fixtures.delete_mutation_branch(canary_public_repo, branch, github_client)


def test_security_review_workflow_has_fork_guard() -> None:
    workflow = (Path(__file__).parents[2] / SECURITY_WORKFLOW_PATH).read_text(encoding="utf-8")

    assert "github.event_name == 'pull_request_target'" in workflow
    assert "github.event.label.name == 'security-review'" in workflow
    assert "github.event.pull_request.head.repo.full_name == github.repository" in workflow
    assert "github.event.pull_request.user.login == 'jclee941'" in workflow

    risky_checkout_ref = re.compile(
        "".join(
            (
                r"uses:\s*actions/checkout@.*?ref:\s*\$[{][{]\s*",
                r"(?:github\.event\.pull_request\.head\.(?:sha|ref)|github\.head_ref)",
            )
        ),
        re.DOTALL,
    )
    assert not risky_checkout_ref.search(workflow), "pull_request_target workflow must not checkout PR head code"
