name: _Test Reusable 2

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Reusable workflow 2 works"
